apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  #encodées en base64
  POSTGRES_USER: bXlkYnVzZXI=
  POSTGRES_PASSWORD: bXlkYnBhc3N3b3Jk
  POSTGRES_DB: bXlkYXRhYmFzZQ==