apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  # Les valeurs doivent être encodées en base64
  # Vous pouvez encoder une valeur avec : echo -n "votre_mot_de_passe" | base64
  POSTGRES_USER: bXlkYnVzZXI=
  POSTGRES_PASSWORD: bXlkYnBhc3N3b3Jk
  POSTGRES_DB: bXlkYXRhYmFzZQ==