apiVersion: apps/v1
kind: Deployment
metadata:
  name: matchmaking
  labels:
    app: matchmaking
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: matchmaking
  template:
    metadata:
      labels:
        app: matchmaking
    spec:
      # nodeSelector:
      #   ingress-ready: "true"
      imagePullSecrets:
        - name: gitlab-registry-auth
      containers:
      - name: matchmaking
        image: registry.gitlab.com/transcendence-group/matchmaking:main-0813ee70
        env:
        - name: JWT_SECRET_KEY
          value: "QlDJQcJgrTbEE72V1yCS469uguODkpK/cii6OLKKBa0="
        - name: GAME_SERVICE_TOKEN
          value: "be1cfe93f3bc0f0f534442328c6191c986e011e18c9fe34d7952c2a50f99fb8b"
        - name: AI_SERVICE_TOKEN
          value: "f2c2f3560b814ff56472a2cdebfe005bcb3ee47df31bd0d41367308d683f935a"
        ports:
        - containerPort: 8001
        volumeMounts:
        - name: ssl-cert
          mountPath: "/etc/nginx/ssl"
          readOnly: true
      volumes:
      - name: ssl-cert
        secret:
          secretName: frontend-ssl-cert
          items:             
              - key: tls.crt  
                path: nginx.crt 
              - key: tls.key
                path: nginx.key