apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller-7777
  namespace: ingress-nginx
  annotations:
    service.beta.kubernetes.io/preserve-client-ip: "true"
spec:
  # ingressClassName: nginx
  type: NodePort
  ports:
  - name: https-7777
    port: 7777
    targetPort: 443
    nodePort: 30777
    protocol: TCP
  selector:
    #labels de l'Ingress Controller
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/component: controller